### PR TITLE
Update docs to improve overall and cover Appsembler changes

### PR DESCRIPTION
**Pull request by bryanlandia**

### CODE REVIEW

**Comment by bryanlandia** [comment]
If anybody is interested in learning about this, especially @amirtds please take a look at these docs.  It's live on staging but not on production yet.

**Comment by bryanlandia** [comment]
@abeals FYI

**Comment by abeals** [comment]
@bryanlandia Thanks for tagging me here. From my read of this, we could potentially generalize this script to process the event logs and send historical data to other destinations as well? Thinking about sending historical info to Segment, for instance... /cc @melvinsoft

**Review by amirtds — APPROVED** [review]
Thanks @bryanlandia the doc looks good. quick question which staging server has xAPI so i can take a quick look ?

**Comment by bryanlandia** [comment]
@amirtds It's installed and running on the ISC Ficus staging server.  Thanks for the review.

**Comment by bryanlandia** [comment]
@abeals Yes, true, we could generalize it if there's a need now. Is there? It's a decent setup so far for watching the tail of tracking logs and taking action.  There's no reason another backend couldn't be set up to process and send data based on parsed tracking logs, like for Segment.  

Otherwise, for xAPI to LRS reporting, and specifically for InterSystems, this is probably an interim solution until edX implements their OEP https://github.com/edx/open-edx-proposals/pull/73.  That could be a year down the road, though—I don't know.   I see the xAPI Client work has been merged to edx-enterprise master—it just reports on registration and completion, though, and requires setting up edx-enterprise, of course. 


cc @melvinsoft

**Pull request merged**
